config/routes.rb
Rails.application.routes.draw do

  get 'report/index'
  get 'expenses/index'
  get 'income/index'
  devise_for :users
	root "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
  end
end

app/controllers/income_controller.rb
class IncomeController < ApplicationController
  def index
  end
end

app/controllers/report_controller.rb
class ReportController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/income_helper.rb
module IncomeHelper
end

app/helpers/report_helper.rb
module ReportHelper
end

app/views/expenses/index.html.erb
<div class="center-xs">
	<h1>Formulario de Egresos</h1>

<div class="">
	<%= render 'egresos' %>
</div>
	

</div>

app/views/home/index.html.erb
<div class="full-reset nav-lateral-list-menu">
    <ul class="list-unstyled">
        <li>
        	<%= link_to "Iniciar sesion", new_user_session_path %>            
        </li>                  
    </ul>
</div>

app/views/income/_ingresos.html.erb
<div class="pan row center-xs panel">

</div>

app/views/income/index.html.erb
<div class="center-xs">
	<h1>Formulario de Ingresos</h1>

<div class="">
	<%= render 'ingresos' %>
</div>
	

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proyectoweb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Alegreya+Sans+SC&display=swap" rel="stylesheet">

    <link rel="Shortcut Icon" type="image/x-icon" href="<%= asset_path 'book.ico' %>" />

  </head>

  <body>

    <% if user_signed_in? %>

    <!-- navegacion vertical -->

    <div class="navbar-lateral full-reset">
      <div class="visible-xs font-movile-menu mobile-menu-button"></div>
      <div class="full-reset container-menu-movile custom-scroll-containers">
        <div class="logo full-reset all-tittles">
          <i class="visible-xs zmdi zmdi-close pull-left mobile-menu-button" style="line-height: 55px; cursor: pointer; padding: 0 10px; margin-left: 7px;"></i> 
          ICE COMPANY
        </div>
        <div class="full-reset" style="background-color:#2B3D51; padding: 10px 0; color:#fff;">
            <figure>
              <img src="<%= asset_path 'L.png' %>" lass="img-responsive center-box" style="width:55%;">
            </figure>
              <p class="text-center" style="padding-top: 15px;">Ice Company s.a.</p>
        </div>
        <div class="full-reset nav-lateral-list-menu">
            <ul class="list-unstyled">
              <li><%= link_to "Inicio", root_path %>                        
              </li>
                    
              <li>
                <%= link_to "Ingresos", income_index_path %> 
              </li>
                    
              <li>
                <%= link_to "Egresos", expenses_index_path %>
              </li>
                    
              <li>
                <%= link_to "Reportes", report_index_path %>
              </li>
            </ul>
        </div>
      </div>
    </div>

    <!-- fin navegacion vertical -->

   

    <div class="content-page-container full-reset custom-scroll-containers">

      <!-- navegacion top -->

        <nav class="navbar-user-top full-reset">
            <ul class="list-unstyled full-reset">
                
                <li style="color:#fff; cursor:default;">
                    <span class="all-tittles">Usuario</span>
                </li>
                <li  class="tooltips-general exit-system-button" data-href="index.html" data-placement="bottom" title="Salir del sistema">
                    <i>
                      <%= link_to "", destroy_user_session_path, method: :delete, class:"zmdi zmdi-power" %>
                    </i>
                </li>
                
                <li class="mobile-menu-button visible-xs" style="float: left !important;">
                    <i class="zmdi zmdi-menu"></i>
                </li>
            </ul>
        </nav>

    <!-- fin navegacion top -->

    <%end%>

    <!-- panel -->

        <%= yield %>

    <!-- fin panel -->
        
      
      <% if user_signed_in? %>

    <!-- pie de pagina -->

        <footer class="footer full-reset">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-xs-12 col-sm-6">
                        <h4 class="all-tittles">Acerca de</h4>
                        <p>
                            Sistema de ingresos y egresos
                        </p>
                    </div>
                    <div class="col-xs-12 col-sm-6">
                        <h4 class="all-tittles">Desarrollador</h4>
                        <ul class="list-unstyled">
                            <li>Equipo de desarrollo Ice Company 
                        </ul>
                    </div>
                </div>
            </div>
            <div class="footer-copyright full-reset all-tittles">© 2020 Ice Company</div>
        </footer>

    <!-- fin pie de pagina -->

    <%end%>

    </div>  
  </body>
</html>

app/views/report/_reportes.html.erb
<div class="container-fluid"  style="margin: 50px 0;">
    <div class="row">
        <div class="col-xs-12 col-sm-4 col-md-3">
            <img src="<%= asset_path 'chart.png' %>" alt="chart" class="img-responsive center-box" style="max-width: 120px;">
        </div>
        <div class="col-xs-12 col-sm-8 col-md-8 text-justify lead">
            Bienvenido al área de reportes, aquí puedes ver los diferentes reportes de los ingresos y egresos.
        </div>
   	</div>

	<br/><br/><br/><br/> <!-- saltos de linea -->

	<div class="container-fluid">
		<div class="row">
			<div class="col-xs-12">
				<%= form_tag("/search", method: "get") do %>
					<%= label_tag(:q, "Filtrar por categoria:") %>
 					<%= text_field_tag(:q) %>
 					<%= submit_tag("Buscar") %>
				<% end %>
     			
     			<%= form_tag("/search", method: "get") do %>
					<%= label_tag(:q, "Filtrar por responsable:") %>
					<%= text_field_tag(:q) %>
					<%= submit_tag("Buscar") %>
				<% end %>
    
 				<%= form_tag("/search", method: "get") do %>
					<%= label_tag(:q, "Filtrar por fecha:") %>
					<%= date_field_tag(:q, :user) %>
					<%= submit_tag("Buscar") %>
				<% end %>
			</div>
		</div>
	</div>

</div>

app/views/report/index.html.erb
<div>
    <div class="page-header">
        <h1 class="all-tittles">Formulario de reportes <small>Inicio</small></h1>
    </div>
</div>

<%= render 'reportes' %>